# Generated by Django 5.1.7 on 2025-05-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template_image', models.ImageField(upload_to='templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(blank=True, null=True, upload_to='originals/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='processed/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
