# Generated by Django 5.1.2 on 2025-01-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='image',
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='original_image',
            field=models.ImageField(default='originals/default.jpg', upload_to='originals/'),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='processed/'),
        ),
    ]
